git:
  depth: 1
sudo: false
language: node_js
node_js:
- 6.11.1
cache:
  yarn: true
before_install:
- openssl aes-256-cbc -K $encrypted_cf61538f352c_key -iv $encrypted_cf61538f352c_iv
  -in credential.json.enc -out ./credential.json -d
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2
install:
- yarn
script:
- yarn test
- yarn run lint
- yarn run flow
