git:
  depth: 1

# Use Dockerized infrastructure
sudo: false

language: node_js
node_js:
  - "6.11.1"

cache:
  yarn: true

before_install:
  # Install yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2

install:
  - yarn

script:
  - yarn test
  - yarn run lint
  - yarn run flow
